apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-world-ns
resources:
  - hello-world-ns.yaml
  - hello-world-deployment.yaml
  - hello-world-service.yaml
  - hello-world-networkpolicy.yaml
commonAnnotations:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: eks-cluster-demo
  docs: docs/kubernetes-deployment-guide.md
images:
  - name: 802645170184.dkr.ecr.us-east-1.amazonaws.com/hello-world-repo
    newTag: 1.2.6
#     # Or use newName to change registry:
#     # newName: newregistry.io/hello-world-repo
# Example: Add config map generator
# configMapGenerator:
#   - name: app-config
#     literals:
#       - APP_ENV=production
#       - LOG_LEVEL=info
replicas:
  - count: 3
    name: hello-world
